package com.example.qrhunter.data.model;

import com.example.qrhunter.utils.QRCodeUtil;

import java.util.ArrayList;

/**
 * Model class for a QRCode
 * TODO: Update the attributes as needed
 */
public class QRCode {
    /**
     * The hash calculated from the QR Code/Bar contents.
     * Note: The hash is not the id of the document in Firestore. The id will be randomly generated by Firestore instead.
     */
    private String hash;

    /**
     * The name generated from the hash
     */
    private String name;

    /**
     * The visual representation generated from the hash
     */
    private String visualRepresentation;

    /**
     * The score of the QR Code calculated from the hash
     */
    private double score;
    private Location location;
    private ArrayList<String> commentIds;

    /**
     * Constructor for a QR Code
     */
    public QRCode(String hash, Location location, ArrayList<String> commentIds) {
        this.hash = hash;

        this.name = QRCodeUtil.generateName(hash);
        this.visualRepresentation = QRCodeUtil.generateVisualRepresentation(hash);
        this.score = QRCodeUtil.generateScore(hash);

        this.location = location;
        this.commentIds = commentIds;
    }


    public String getHash() {
        return hash;
    }

    public void setHash(String hash) {
        this.hash = hash;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getVisualRepresentation() {
        return visualRepresentation;
    }

    public void setVisualRepresentation(String visualRepresentation) {
        this.visualRepresentation = visualRepresentation;
    }

    public double getScore() {
        return score;
    }

    public void setScore(double score) {
        this.score = score;
    }

    public Location getLocation() {
        return location;
    }

    public void setLocation(Location location) {
        this.location = location;
    }

    public ArrayList<String> getCommentIds() {
        return commentIds;
    }

    public void setCommentIds(ArrayList<String> commentIds) {
        this.commentIds = commentIds;
    }
}

