name: Android CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: gradle
    - name: Access MAPS_API_KEY
      working-directory: ./QRHunter
      env:
        MAPS_API_KEY: ${{ secrets.MAPS_API_KEY }}
      run: echo MAPS_API_KEY=\"$ MAPS_API_KEY\" > ./local.properties

    - name: Grant execute permission for gradlew
      working-directory: ./QRHunter
      run: chmod +x gradlew
    - name: Build with Gradle
      working-directory: ./QRHunter
      run: ./gradlew build
